pipeline {
    agent any
    stages {
        stage('Build') {
            steps {
                echo "building the image"
            }
        }
        stage('Test') {
            steps {
                echo "building the image"
            }
        }
    }
}
