        stage('Deliver for development') {
            when {
                branch 'master'
            }
            steps {
                    echo "testing the master branch"
            }
        }
        stage('Deploy for production') {
            when {
                branch '	bitwiseman-patch-1'
            }
            steps {
              echo "testing the bitwiseman-patch-1"
            }
        }
